// Auto-generated by LCARS Designer - DO NOT EDIT
// Re-generate by saving layout in the designer
#pragma once

// ---- Claude.ai ----
#define CAI_5H_X  96
#define CAI_5H_Y  104
#define CAI_5H_W  76
#define CAI_5H_T  7
#define CAI_5H_PCT_FONT  LCARS_MD
#define CAI_5H_PCT_COLOR  CLR_TEXT_BRIGHT
#define CAI_7D_X  240
#define CAI_7D_Y  104
#define CAI_7D_W  76
#define CAI_7D_T  7
#define CAI_7D_PCT_FONT  LCARS_MD
#define CAI_7D_PCT_COLOR  CLR_TEXT_BRIGHT
#define CAI_5H_LABEL_X  96
#define CAI_5H_LABEL_Y  24
#define CAI_5H_LABEL_FONT  LCARS_26
#define CAI_5H_LABEL_COLOR  CLR_TEXT_BRIGHT
#define CAI_5H_LABEL_DATUM  TC_DATUM
#define CAI_7D_LABEL_X  241
#define CAI_7D_LABEL_Y  24
#define CAI_7D_LABEL_FONT  LCARS_26
#define CAI_7D_LABEL_COLOR  CLR_PEACH
#define CAI_7D_LABEL_DATUM  TC_DATUM
#define CAI_5H_CD_X  152
#define CAI_5H_CD_Y  24
#define CAI_5H_CD_W  12
#define CAI_5H_CD_H  120
#define CAI_7D_CD_X  296
#define CAI_7D_CD_Y  24
#define CAI_7D_CD_W  12
#define CAI_7D_CD_H  120
#define CUSTOM_SIGNALLABEL_15_X  172
#define CUSTOM_SIGNALLABEL_15_Y  164
#define CUSTOM_VLINE_18_X  180
#define CUSTOM_VLINE_18_Y  24
#define CUSTOM_VLINE_18_H  120

// ---- Overview ----
#define LBL_TODAY_X  52
#define LBL_TODAY_Y  26
#define LBL_TODAY_FONT  LCARS_SM
#define LBL_TODAY_COLOR  CLR_AMBER
#define LBL_TODAY_DATUM  TL_DATUM
#define COST_TODAY_X  52
#define COST_TODAY_Y  38
#define LBL_MONTH_X  52
#define LBL_MONTH_Y  88
#define LBL_MONTH_FONT  LCARS_SM
#define LBL_MONTH_COLOR  CLR_AMBER
#define LBL_MONTH_DATUM  TL_DATUM
#define COST_MONTH_X  52
#define COST_MONTH_Y  104
#define DIV_MAIN_X  181
#define DIV_MAIN_Y  30
#define DIV_MAIN_H  134
#define LBL_BREAKDOWN_X  188
#define LBL_BREAKDOWN_Y  26
#define LBL_BREAKDOWN_FONT  LCARS_SM
#define LBL_BREAKDOWN_COLOR  CLR_AMBER
#define LBL_BREAKDOWN_DATUM  TL_DATUM
#define COST_MODEL_0_X  188
#define COST_MODEL_0_Y  44
#define COST_MODEL_0_W  126
#define COST_MODEL_1_X  188
#define COST_MODEL_1_Y  69
#define COST_MODEL_1_W  126
#define COST_MODEL_2_X  188
#define COST_MODEL_2_Y  94
#define COST_MODEL_2_W  126
#define CUSTOM_SIGNALLABEL_8_X  172
#define CUSTOM_SIGNALLABEL_8_Y  164
#define CUSTOM_VLINE_19_X  180
#define CUSTOM_VLINE_19_Y  24
#define CUSTOM_VLINE_19_H  120
#define COST_MODEL_START_Y  44
#define COST_MODEL_ROW_STEP  25

// ---- Models ----
#define TM_MODEL_0_X  52
#define TM_MODEL_0_Y  26
#define TM_MODEL_0_W  264
#define TM_MODEL_1_X  52
#define TM_MODEL_1_Y  50
#define TM_MODEL_1_W  264
#define TM_MODEL_2_X  52
#define TM_MODEL_2_Y  74
#define TM_MODEL_2_W  264
#define CUSTOM_SIGNALLABEL_9_X  172
#define CUSTOM_SIGNALLABEL_9_Y  164
#define TM_MODEL_START_Y  26
#define TM_MODEL_ROW_STEP  24

// ---- Monthly Models ----
#define MM_MODEL_0_X  52
#define MM_MODEL_0_Y  26
#define MM_MODEL_0_W  264
#define MM_MODEL_1_X  52
#define MM_MODEL_1_Y  50
#define MM_MODEL_1_W  264
#define MM_MODEL_2_X  52
#define MM_MODEL_2_Y  74
#define MM_MODEL_2_W  264
#define CUSTOM_SIGNALLABEL_10_X  172
#define CUSTOM_SIGNALLABEL_10_Y  164
#define MM_MODEL_START_Y  26
#define MM_MODEL_ROW_STEP  24

// ---- Code ----
#define TC_SEC_SESSIONS_X  52
#define TC_SEC_SESSIONS_Y  26
#define TC_VAL_SESSIONS_X  176
#define TC_VAL_SESSIONS_Y  26
#define TC_VAL_SESSIONS_FONT  LCARS_MD
#define TC_VAL_SESSIONS_COLOR  CLR_TEXT_BRIGHT
#define TC_VAL_SESSIONS_DATUM  TR_DATUM
#define TC_SEC_LINES_X  52
#define TC_SEC_LINES_Y  50
#define TC_VAL_LINES_X  176
#define TC_VAL_LINES_Y  66
#define TC_VAL_LINES_FONT  LCARS_SM
#define TC_VAL_LINES_COLOR  CLR_SKY
#define TC_VAL_LINES_DATUM  TR_DATUM
#define TC_ROW_COMMITS_X  52
#define TC_ROW_COMMITS_Y  84
#define TC_ROW_COMMITS_W  124
#define TC_ROW_PRS_X  52
#define TC_ROW_PRS_Y  102
#define TC_ROW_PRS_W  124
#define TC_LBL_COST_X  52
#define TC_LBL_COST_Y  120
#define TC_LBL_COST_FONT  LCARS_SM
#define TC_LBL_COST_COLOR  CLR_AMBER
#define TC_LBL_COST_DATUM  TL_DATUM
#define TC_VAL_COST_X  176
#define TC_VAL_COST_Y  120
#define TC_VAL_COST_FONT  LCARS_SM
#define TC_VAL_COST_COLOR  CLR_SKY
#define TC_VAL_COST_DATUM  TR_DATUM
#define TC_DIV_X  182
#define TC_DIV_Y  30
#define TC_DIV_H  122
#define TC_SEC_ACCEPT_X  188
#define TC_SEC_ACCEPT_Y  26
#define TC_BAR_EDIT_X  188
#define TC_BAR_EDIT_Y  44
#define TC_BAR_EDIT_W  126
#define TC_BAR_WRITE_X  188
#define TC_BAR_WRITE_Y  62
#define TC_BAR_WRITE_W  126
#define TC_HLINE_X  188
#define TC_HLINE_Y  82
#define TC_HLINE_W  126
#define TC_SEC_USERS_X  188
#define TC_SEC_USERS_Y  98
#define TC_ROW_USER_X  188
#define TC_ROW_USER_Y  116
#define TC_ROW_USER_W  126
#define CUSTOM_SIGNALLABEL_11_X  172
#define CUSTOM_SIGNALLABEL_11_Y  164

// ---- Monthly Code ----
#define MC_SEC_SESSIONS_X  52
#define MC_SEC_SESSIONS_Y  26
#define MC_VAL_SESSIONS_X  176
#define MC_VAL_SESSIONS_Y  26
#define MC_VAL_SESSIONS_FONT  LCARS_MD
#define MC_VAL_SESSIONS_COLOR  CLR_TEXT_BRIGHT
#define MC_VAL_SESSIONS_DATUM  TR_DATUM
#define MC_SEC_LINES_X  52
#define MC_SEC_LINES_Y  50
#define MC_VAL_LINES_X  176
#define MC_VAL_LINES_Y  66
#define MC_VAL_LINES_FONT  LCARS_SM
#define MC_VAL_LINES_COLOR  CLR_SKY
#define MC_VAL_LINES_DATUM  TR_DATUM
#define MC_ROW_COMMITS_X  52
#define MC_ROW_COMMITS_Y  84
#define MC_ROW_COMMITS_W  124
#define MC_ROW_PRS_X  52
#define MC_ROW_PRS_Y  102
#define MC_ROW_PRS_W  124
#define MC_LBL_COST_X  52
#define MC_LBL_COST_Y  120
#define MC_LBL_COST_FONT  LCARS_SM
#define MC_LBL_COST_COLOR  CLR_AMBER
#define MC_LBL_COST_DATUM  TL_DATUM
#define MC_VAL_COST_X  176
#define MC_VAL_COST_Y  120
#define MC_VAL_COST_FONT  LCARS_SM
#define MC_VAL_COST_COLOR  CLR_SKY
#define MC_VAL_COST_DATUM  TR_DATUM
#define MC_DIV_X  182
#define MC_DIV_Y  30
#define MC_DIV_H  122
#define MC_SEC_ACCEPT_X  188
#define MC_SEC_ACCEPT_Y  26
#define MC_BAR_EDIT_X  188
#define MC_BAR_EDIT_Y  44
#define MC_BAR_EDIT_W  126
#define MC_BAR_WRITE_X  188
#define MC_BAR_WRITE_Y  62
#define MC_BAR_WRITE_W  126
#define MC_HLINE_X  188
#define MC_HLINE_Y  82
#define MC_HLINE_W  126
#define MC_SEC_USERS_X  188
#define MC_SEC_USERS_Y  98
#define MC_ROW_USER_X  188
#define MC_ROW_USER_Y  116
#define MC_ROW_USER_W  126
#define CUSTOM_SIGNALLABEL_12_X  172
#define CUSTOM_SIGNALLABEL_12_Y  164

// ---- Status ----
#define ST_SEC_NET_X  52
#define ST_SEC_NET_Y  26
#define ST_WIFI_X  52
#define ST_WIFI_Y  42
#define ST_WIFI_W  124
#define ST_IP_X  52
#define ST_IP_Y  58
#define ST_IP_W  124
#define ST_SIGNAL_X  52
#define ST_SIGNAL_Y  74
#define ST_SIGNAL_W  102
#define ST_BARS_X  158
#define ST_BARS_Y  75
#define ST_SEC_API_X  52
#define ST_SEC_API_Y  96
#define ST_API_X  52
#define ST_API_Y  112
#define ST_API_W  124
#define ST_FETCHED_X  52
#define ST_FETCHED_Y  128
#define ST_FETCHED_W  124
#define ST_DIV_X  182
#define ST_DIV_Y  30
#define ST_DIV_H  122
#define ST_SEC_SYS_X  188
#define ST_SEC_SYS_Y  26
#define ST_HEAP_X  188
#define ST_HEAP_Y  42
#define ST_HEAP_W  126
#define ST_PSRAM_X  188
#define ST_PSRAM_Y  58
#define ST_PSRAM_W  126
#define ST_UPTIME_X  188
#define ST_UPTIME_Y  74
#define ST_UPTIME_W  126
#define ST_SEC_FW_X  188
#define ST_SEC_FW_Y  96
#define ST_FW_VER_X  188
#define ST_FW_VER_Y  112
#define ST_FW_VER_FONT  LCARS_SM
#define ST_FW_VER_COLOR  CLR_TEXT_DIM
#define ST_FW_VER_DATUM  TL_DATUM
#define ST_BOARD_X  188
#define ST_BOARD_Y  128
#define ST_BOARD_FONT  LCARS_SM
#define ST_BOARD_COLOR  CLR_TEXT_DIM
#define ST_BOARD_DATUM  TL_DATUM
#define CUSTOM_SIGNALLABEL_13_X  172
#define CUSTOM_SIGNALLABEL_13_Y  164

// ---- Page 8 ----
#define CUSTOM_SIGNALLABEL_14_X  172
#define CUSTOM_SIGNALLABEL_14_Y  164

// ---- Frame Chrome ----
#define FRAME_PAGE_X  52
#define FRAME_PAGE_Y  157
#define FRAME_PAGE_W  28
#define FRAME_PAGE_H  14
#define FRAME_PAGE_COLOR  CLR_PEACH
#define FRAME_SIGNAL_BARS_X  176
#define FRAME_SIGNAL_BARS_Y  158
#define FRAME_COUNTDOWN_X  200
#define FRAME_COUNTDOWN_Y  157
#define FRAME_COUNTDOWN_W  120
#define FRAME_COUNTDOWN_H  14
#define FRAME_COUNTDOWN_COLOR  CLR_AMBER
#define FRAME_CLAUDE_X  294
#define FRAME_CLAUDE_Y  8
#define FRAME_CLAUDE_COLOR  CLR_PEACH
#define FRAME_CLAUDE_FONT  LCARS_MD
#define FRAME_CLAUDE_TEXT  "CLAUDE"
#define FRAME_SIGNAL_TEXT_X  172
#define FRAME_SIGNAL_TEXT_Y  161
#define FRAME_SIGNAL_TEXT_COLOR  CLR_TEXT_DIM
#define FRAME_SIGNAL_TEXT_FONT  1
#define FRAME_SIGNAL_TEXT_TEXT  "SIGNAL"

// ---- Custom Elements ----
#include <cstdint>
struct CustomTextEl { int16_t x; int16_t y; const char* text; const uint8_t* font; uint16_t color; };

#define CUSTOM_SCREEN_0_COUNT  0

#define CUSTOM_SCREEN_1_COUNT  0

#define CUSTOM_SCREEN_2_COUNT  0

#define CUSTOM_SCREEN_3_COUNT  0

#define CUSTOM_SCREEN_4_COUNT  0

#define CUSTOM_SCREEN_5_COUNT  0

#define CUSTOM_SCREEN_6_COUNT  0

#define CUSTOM_SCREEN_7_COUNT  0

