#!/usr/bin/env python3
"""
Convert Antonio.ttf to TFT_eSPI VLW smooth font C header files.
Generates anti-aliased font data for 3 sizes (12, 18, 28px).

Usage:  python tools/create_smooth_fonts.py
Output: include/smooth_font_12.h, smooth_font_18.h, smooth_font_28.h
"""

from PIL import Image, ImageDraw, ImageFont
import struct, os, sys, json, base64

FONT_PATH = os.path.join(os.path.dirname(__file__), "Antonio.ttf")
OUT_DIR   = os.path.join(os.path.dirname(__file__), "..", "include")

# ASCII printable range (space through tilde)
CHARS = [chr(c) for c in range(32, 127)]


def get_glyph_data(font, char):
    """Render a single character and extract VLW metrics + alpha bitmap."""
    ascent, descent = font.getmetrics()
    canvas_sz = ascent + descent + 20  # generous canvas

    # Render character with anti-aliasing (grayscale)
    img = Image.new('L', (canvas_sz * 2, canvas_sz), 0)
    draw = ImageDraw.Draw(img)
    draw.text((10, 0), char, fill=255, font=font)

    # Find tight bounding box of non-zero pixels
    pixels = img.load()
    w_img, h_img = img.size
    left = top = None
    right = bottom = 0

    for py in range(h_img):
        for px in range(w_img):
            if pixels[px, py] > 0:
                if left is None:
                    left = px
                    top = py
                left = min(left, px)
                right = max(right, px)
                top = min(top, py)
                bottom = max(bottom, py)

    xAdvance = int(round(font.getlength(char)))

    if left is None:
        # Empty glyph (space character)
        return {
            'unicode': ord(char),
            'width': 0, 'height': 0,
            'xAdvance': xAdvance,
            'dY': 0, 'dX': 0,
            'bitmap': b''
        }

    gw = right - left + 1
    gh = bottom - top + 1

    # Extract alpha bitmap (row-major)
    bitmap = bytearray()
    for py in range(top, bottom + 1):
        for px in range(left, right + 1):
            bitmap.append(pixels[px, py])

    # Metrics relative to baseline
    # Pillow draws with ascent line at y=0, baseline at y=ascent
    # We drew at x=10, y=0
    gdY = ascent - top        # baseline to top of glyph (positive = above baseline)
    gdX = left - 10           # left bearing relative to cursor (x=10 was our origin)

    return {
        'unicode': ord(char),
        'width': gw, 'height': gh,
        'xAdvance': xAdvance,
        'dY': gdY, 'dX': gdX,
        'bitmap': bytes(bitmap)
    }


def create_vlw(font_path, size):
    """Create VLW binary data from a TTF font at given pixel size."""
    font = ImageFont.truetype(font_path, size)
    ascent, descent = font.getmetrics()

    glyphs = []
    for ch in CHARS:
        glyphs.append(get_glyph_data(font, ch))

    # Calculate maxAscent / maxDescent from actual glyph data
    max_ascent = 0
    max_descent = 0
    for g in glyphs:
        if g['height'] > 0:
            max_ascent = max(max_ascent, g['dY'])
            max_descent = max(max_descent, g['height'] - g['dY'])

    # Build VLW binary (big-endian)
    data = bytearray()

    # Header: 6 x uint32_t = 24 bytes
    data += struct.pack('>I', len(glyphs))   # gCount
    data += struct.pack('>I', 11)            # version (0x0B)
    data += struct.pack('>I', size)          # fontSize (used as yAdvance)
    data += struct.pack('>I', 0)             # mboxY (deprecated)
    data += struct.pack('>I', ascent)        # ascent
    data += struct.pack('>I', descent)       # descent

    # Glyph metrics: 7 x uint32_t = 28 bytes per glyph
    for g in glyphs:
        data += struct.pack('>I', g['unicode'])
        data += struct.pack('>I', g['height'])
        data += struct.pack('>I', g['width'])
        data += struct.pack('>I', g['xAdvance'])
        data += struct.pack('>i', g['dY'])       # signed
        data += struct.pack('>i', g['dX'])       # signed
        data += struct.pack('>I', 0)             # padding

    # Bitmap data (sequential)
    for g in glyphs:
        data += g['bitmap']

    total_bitmap = sum(len(g['bitmap']) for g in glyphs)
    print(f"  Size {size}px: {len(glyphs)} glyphs, ascent={ascent}, descent={descent}, "
          f"maxAscent={max_ascent}, maxDescent={max_descent}, "
          f"bitmap={total_bitmap} bytes, total={len(data)} bytes")

    return bytes(data)


def write_header(vlw_data, size, out_path):
    """Write VLW data as a C header file with PROGMEM array."""
    name = f"SmoothFont{size}"

    lines = []
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append(f"// Antonio Regular {size}px - VLW smooth font for TFT_eSPI")
    lines.append(f"// Generated by tools/create_smooth_fonts.py")
    lines.append(f"// {len(vlw_data)} bytes ({len(vlw_data) / 1024:.1f} KB)")
    lines.append("")
    lines.append(f"const uint8_t {name}[] PROGMEM = {{")

    # Format as hex bytes, 16 per line
    for i in range(0, len(vlw_data), 16):
        chunk = vlw_data[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        if i + 16 < len(vlw_data):
            hex_str += ","
        lines.append(f"    {hex_str}")

    lines.append("};")
    lines.append("")

    with open(out_path, 'w') as f:
        f.write("\n".join(lines))

    print(f"  Wrote {out_path} ({len(vlw_data) / 1024:.1f} KB)")


def main():
    if not os.path.exists(FONT_PATH):
        print(f"Error: Font not found at {FONT_PATH}")
        sys.exit(1)

    os.makedirs(OUT_DIR, exist_ok=True)

    sizes = [12, 14, 16, 18, 20, 22, 24, 26, 28, 36]

    print("Converting Antonio.ttf to VLW smooth fonts...")
    for size in sizes:
        vlw = create_vlw(FONT_PATH, size)
        out = os.path.join(OUT_DIR, f"smooth_font_{size}.h")
        write_header(vlw, size, out)

    # Also generate font atlas JSON for the designer (pixel-perfect rendering)
    designer_dir = os.path.join(os.path.dirname(__file__), "..", "..", "designer")
    atlas = {}
    for size in sizes:
        font = ImageFont.truetype(FONT_PATH, size)
        glyphs = {}
        max_asc = 0
        max_desc = 0
        for ch in CHARS:
            g = get_glyph_data(font, ch)
            entry = {
                "w": g["width"], "h": g["height"],
                "xAdv": g["xAdvance"],
                "dY": g["dY"], "dX": g["dX"],
            }
            if g["bitmap"]:
                entry["bmp"] = base64.b64encode(g["bitmap"]).decode("ascii")
            glyphs[ch] = entry
            if g["height"] > 0:
                max_asc = max(max_asc, g["dY"])
                max_desc = max(max_desc, g["height"] - g["dY"])
        atlas[str(size)] = {
            "maxAscent": max_asc,
            "maxDescent": max_desc,
            "yAdvance": max_asc + max_desc,
            "glyphs": glyphs,
        }

    atlas_path = os.path.join(designer_dir, "font_atlas.json")
    with open(atlas_path, "w") as f:
        json.dump(atlas, f, separators=(",", ":"))
    print(f"  Wrote {atlas_path} ({os.path.getsize(atlas_path) / 1024:.0f} KB)")

    print("\nDone! Smooth font headers generated in include/")


if __name__ == "__main__":
    main()
