#!/usr/bin/env python3
"""
LCARS Designer Server
Serves the designer UI, persists layouts, generates C++ headers, triggers builds.
Zero external dependencies — uses only Python stdlib.

Usage:
    python designer/server.py
    Open http://localhost:8080
"""

import http.server
import json
import os
import re
import subprocess
import sys
import threading
import time
from pathlib import Path
from urllib.parse import urlparse, parse_qs

# ============================================================
# Paths
# ============================================================
DESIGNER_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = DESIGNER_DIR.parent
FIRMWARE_V1_DIR = PROJECT_ROOT / "firmware"
FIRMWARE_V2_DIR = PROJECT_ROOT / "firmware-v2"
LAYOUTS_FILE = DESIGNER_DIR / "layouts.json"
HEADER_FILE = FIRMWARE_V1_DIR / "include" / "screen_layouts.h"
HEADER_V2_FILE = FIRMWARE_V2_DIR / "include" / "screen_layouts.h"

PORT = 8080

# Board name -> PlatformIO environment
ENV_MAP = {
    "tdisplay": "tdisplays3",
    "waveshare": "waveshare147"
}

# ============================================================
# Find PlatformIO
# ============================================================
def find_pio():
    """Find the pio executable."""
    # Try PATH first
    import shutil
    pio = shutil.which("pio")
    if pio:
        return pio
    # Windows fallback
    win_path = Path.home() / ".platformio" / "penv" / "Scripts" / "pio.exe"
    if win_path.exists():
        return str(win_path)
    return "pio"  # Hope for the best

PIO_CMD = find_pio()

# ============================================================
# Header Generation
# ============================================================
def generate_header(layouts: dict) -> str:
    """Generate screen_layouts.h from saved layout positions."""
    lines = [
        "// Auto-generated by LCARS Designer - DO NOT EDIT",
        "// Re-generate by saving layout in the designer",
        "#pragma once",
        "",
    ]

    # Merge customElements into screens for export
    custom_by_screen = {}
    for ce in layouts.get("customElements", []):
        si = ce.get("screen", -1)
        if si >= 0 and ce.get("elements"):
            custom_by_screen[si] = ce["elements"]

    for si, screen in enumerate(layouts.get("screens", [])):
        screen_name = screen.get("name", "Unknown")
        lines.append(f"// ---- {screen_name} ----")

        # Track sequences for loop elements (e.g., cost_model_0, cost_model_1)
        sequences = {}  # base_id -> [(index, element)]

        all_els = list(screen.get("elements", []))
        all_els.extend(custom_by_screen.get(si, []))

        for el in all_els:
            eid = el.get("id", "")
            if not eid or eid.startswith("screen_title"):
                continue
            if eid.startswith("frame_"):
                continue  # frame elements handled separately below

            # Check if this is a sequence element (ends with _N)
            seq_match = re.match(r'^(.+)_(\d+)$', eid)
            if seq_match:
                base_id = seq_match.group(1)
                idx = int(seq_match.group(2))
                if base_id not in sequences:
                    sequences[base_id] = []
                sequences[base_id].append((idx, el))

            define_name = eid.upper()
            lines.append(f"#define {define_name}_X  {el['x']}")
            lines.append(f"#define {define_name}_Y  {el['y']}")
            if "w" in el:
                lines.append(f"#define {define_name}_W  {el['w']}")
            elif "r" in el:
                # Donut gauges: export diameter as W, applying scale if present
                scale = el.get("scale", 1)
                r_scaled = int(el['r'] * scale)
                lines.append(f"#define {define_name}_W  {r_scaled * 2}")
                # Export scaled thickness for donut gauges
                if el.get("type") == "donutGauge":
                    thk = el.get("thickness", 7)
                    lines.append(f"#define {define_name}_T  {max(2, int(thk * scale))}")
            elif el.get("type") == "donutGauge":
                # Default donut radius is 38
                scale = el.get("scale", 1)
                lines.append(f"#define {define_name}_W  {int(38 * scale) * 2}")
                thk = el.get("thickness", 7)
                lines.append(f"#define {define_name}_T  {max(2, int(thk * scale))}")
            if "h" in el:
                lines.append(f"#define {define_name}_H  {el['h']}")
            # Text element font/color (for standalone labels like countdown text)
            if el.get("type") == "text" and "font" in el:
                font_map = {
                    "builtin": "1", "sm": "LCARS_SM", "14": "LCARS_14", "16": "LCARS_16",
                    "md": "LCARS_MD", "20": "LCARS_20", "22": "LCARS_22", "24": "LCARS_24",
                    "26": "LCARS_26", "lg": "LCARS_LG", "xl": "LCARS_XL",
                }
                fw_font = font_map.get(el["font"], "LCARS_SM")
                lines.append(f"#define {define_name}_FONT  {fw_font}")
            if el.get("type") == "text" and "color" in el:
                lines.append(f"#define {define_name}_COLOR  {el['color']}")
            if el.get("type") == "text" and "datum" in el:
                datum_map = {
                    "TL": "TL_DATUM", "TC": "TC_DATUM", "TR": "TR_DATUM",
                    "MC": "MC_DATUM", "ML": "ML_DATUM", "MR": "MR_DATUM",
                }
                fw_datum = datum_map.get(el["datum"], "TL_DATUM")
                lines.append(f"#define {define_name}_DATUM  {fw_datum}")
            # Donut gauge pct font/color
            if el.get("type") == "donutGauge":
                pct_font = el.get("pctFont", "md")
                pct_color = el.get("pctColor", "CLR_TEXT_BRIGHT")
                pct_font_map = {
                    "builtin": "1", "sm": "LCARS_SM", "14": "LCARS_14", "16": "LCARS_16",
                    "md": "LCARS_MD", "20": "LCARS_20", "22": "LCARS_22", "24": "LCARS_24",
                    "26": "LCARS_26", "lg": "LCARS_LG", "xl": "LCARS_XL",
                }
                fw_pct_font = pct_font_map.get(pct_font, "LCARS_MD")
                lines.append(f"#define {define_name}_PCT_FONT  {fw_pct_font}")
                lines.append(f"#define {define_name}_PCT_COLOR  {pct_color}")

        # Emit START_Y and ROW_STEP for detected sequences
        for base_id, items in sequences.items():
            if len(items) < 2:
                continue
            items.sort(key=lambda x: x[0])
            start_y = items[0][1]["y"]
            step = items[1][1]["y"] - items[0][1]["y"]
            if step > 0:
                define_base = base_id.upper()
                lines.append(f"#define {define_base}_START_Y  {start_y}")
                lines.append(f"#define {define_base}_ROW_STEP  {step}")

        lines.append("")

    # Generate frame element defines (shared across all screens)
    # Search all screens for frame elements, use first occurrence of each
    frame_by_id = {}
    for screen in layouts.get("screens", []):
        for e in screen.get("elements", []):
            eid = e.get("id", "")
            if eid.startswith("frame_") and eid not in frame_by_id:
                frame_by_id[eid] = e
    # Ensure essential frame elements have defaults even if deleted from all screens
    scr_w = 320  # default T-Display-S3
    board = layouts.get("board", "tdisplay")
    if board == "waveshare147":
        scr_w = 172
    essential_defaults = {
        "frame_claude": {"id": "frame_claude", "x": scr_w - 6, "y": 8, "font": "14", "color": "CLR_BG", "text": "CLAUDE.AI"},
        "frame_signal_text": {"id": "frame_signal_text", "x": scr_w - 148, "y": scr_w == 320 and 161 or 158, "font": "builtin", "color": "CLR_TEXT_DIM", "text": "SIGNAL"},
        "frame_signal_bars": {"id": "frame_signal_bars", "x": scr_w - 144, "y": scr_w == 320 and 156 or 153},
        "frame_countdown": {"id": "frame_countdown", "x": scr_w - 120, "y": scr_w == 320 and 155 or 152, "w": 120, "h": 14, "color": "CLR_AMBER"},
    }
    for eid, defaults in essential_defaults.items():
        if eid not in frame_by_id:
            frame_by_id[eid] = defaults
    frame_els = list(frame_by_id.values())
    if frame_els:
        lines.append("// ---- Frame Chrome ----")
        for el in frame_els:
            eid = el["id"]
            define_name = eid.upper()
            lines.append(f"#define {define_name}_X  {el['x']}")
            lines.append(f"#define {define_name}_Y  {el['y']}")
            if "w" in el:
                lines.append(f"#define {define_name}_W  {el['w']}")
            if "h" in el:
                lines.append(f"#define {define_name}_H  {el['h']}")
            if "color" in el:
                lines.append(f"#define {define_name}_COLOR  {el['color']}")
            if "font" in el:
                # Map designer font keys to firmware defines
                font_map = {
                    "builtin": "1", "sm": "LCARS_SM", "14": "LCARS_14", "16": "LCARS_16",
                    "md": "LCARS_MD", "20": "LCARS_20", "22": "LCARS_22", "24": "LCARS_24",
                    "26": "LCARS_26", "lg": "LCARS_LG", "xl": "LCARS_XL",
                }
                fw_font = font_map.get(el["font"], "LCARS_SM")
                lines.append(f"#define {define_name}_FONT  {fw_font}")
            if "text" in el:
                lines.append(f'#define {define_name}_TEXT  "{el["text"]}"')
        lines.append("")

    # Generate custom element arrays per screen
    # Maps designer font/color keys to firmware identifiers
    font_map = {
        "builtin": "nullptr", "sm": "LCARS_SM", "14": "LCARS_14", "16": "LCARS_16",
        "md": "LCARS_MD", "20": "LCARS_20", "22": "LCARS_22", "24": "LCARS_24",
        "26": "LCARS_26", "lg": "LCARS_LG", "xl": "LCARS_XL",
    }
    has_custom = any(custom_by_screen.get(i) for i in range(len(layouts.get("screens", []))))
    if has_custom:
        lines.append("// ---- Custom Elements ----")
        lines.append("#include <cstdint>")
        lines.append("struct CustomTextEl { int16_t x; int16_t y; const char* text; const uint8_t* font; uint16_t color; };")
        lines.append("")

        screen_names = layouts.get("screens", [])
        for si in range(len(screen_names)):
            els = custom_by_screen.get(si, [])
            text_els = [e for e in els if e.get("type") in ("text", "sectionHeader")]
            arr_name = f"CUSTOM_SCREEN_{si}"
            if text_els:
                lines.append(f"static const CustomTextEl {arr_name}[] = {{")
                for el in text_els:
                    x = el.get("x", 0)
                    y = el.get("y", 0)
                    text = el.get("text", "").replace('"', '\\"')
                    font = font_map.get(el.get("font", "sm"), "LCARS_SM")
                    color = el.get("color", "CLR_AMBER")
                    lines.append(f'    {{ {x}, {y}, "{text}", {font}, {color} }},')
                lines.append("};")
                lines.append(f"#define {arr_name}_COUNT  {len(text_els)}")
            else:
                lines.append(f"#define {arr_name}_COUNT  0")
            lines.append("")

    return "\n".join(lines) + "\n"


def generate_header_v2(layouts: dict) -> str:
    """Generate screen_layouts.h for firmware-v2 (lcars-esp32 engine).

    Maps designer element IDs to #define macros with positions, sizes, and
    font/datum values using lcars-esp32's LcarsFontSize enum names.
    """
    # lcars-esp32 uses LCARS_FONT_* enum values (not v1's LCARS_SM shorthand)
    v2_font_map = {
        "builtin": "1",
        "sm": "LCARS_FONT_SM", "14": "LCARS_FONT_14", "16": "LCARS_FONT_16",
        "md": "LCARS_FONT_MD", "20": "LCARS_FONT_20",
        "22": "LCARS_FONT_20",   # no 22px in engine, use closest
        "24": "LCARS_FONT_LG",   # no 24px in engine, use closest (28px)
        "26": "LCARS_FONT_LG",   # no 26px in engine, use closest (28px)
        "lg": "LCARS_FONT_LG", "xl": "LCARS_FONT_XL",
    }
    datum_map = {
        "TL": "TL_DATUM", "TC": "TC_DATUM", "TR": "TR_DATUM",
        "MC": "MC_DATUM", "ML": "ML_DATUM", "MR": "MR_DATUM",
    }
    # Map designer CLR_ names to lcars-esp32 LCARS_ color constants
    color_map = {
        "CLR_BG": "LCARS_BLACK",
        "CLR_AMBER": "LCARS_AMBER",
        "CLR_SALMON": "LCARS_TOMATO",
        "CLR_PEACH": "LCARS_PEACH",
        "CLR_LAVENDER": "LCARS_LAVENDER",
        "CLR_BLUE": "LCARS_PERIWINKLE",
        "CLR_ORANGE": "LCARS_ORANGE",
        "CLR_RED": "LCARS_MARS",
        "CLR_SKY": "LCARS_ICE",
        "CLR_TAN": "LCARS_TAN",
        "CLR_TEXT_BRIGHT": "LCARS_WHITE",
        "CLR_TEXT_DIM": "LCARS_TEXT_DIM",
        "CLR_BAR_BG": "LCARS_BAR_TRACK",
        "CLR_STATUS_OK": "LCARS_ICE",
        "CLR_STATUS_ERR": "LCARS_TOMATO",
        "CLR_ICE": "LCARS_ICE",
    }

    def map_color(c):
        return color_map.get(c, c)

    lines = [
        "// Auto-generated by LCARS Designer for firmware-v2 — DO NOT EDIT",
        "// Re-generate by saving/building in the designer",
        "#pragma once",
        "",
    ]

    for si, screen in enumerate(layouts.get("screens", [])):
        screen_name = screen.get("name", "Unknown")
        lines.append(f"// ---- Screen {si}: {screen_name} ----")

        for el in screen.get("elements", []):
            eid = el.get("id", "")
            if not eid or eid.startswith("screen_title"):
                continue
            if eid.startswith("frame_"):
                continue  # frame chrome handled below

            define_name = eid.upper()
            el_type = el.get("type", "")

            # Position (all elements)
            lines.append(f"#define {define_name}_X  {el['x']}")
            lines.append(f"#define {define_name}_Y  {el['y']}")

            # Donut gauge: emit diameter (W), thickness (T), pct font/color
            if el_type == "donutGauge":
                scale = el.get("scale", 1)
                r = el.get("r", 38)
                r_scaled = int(r * scale)
                thk = el.get("thickness", 7)
                thk_scaled = max(2, int(thk * scale))
                lines.append(f"#define {define_name}_R  {r_scaled}")
                lines.append(f"#define {define_name}_T  {thk_scaled}")
                pct_font = el.get("pctFont", "md")
                pct_color = el.get("pctColor", "CLR_TEXT_BRIGHT")
                lines.append(f"#define {define_name}_PCT_FONT  {v2_font_map.get(pct_font, 'LCARS_FONT_MD')}")
                lines.append(f"#define {define_name}_PCT_COLOR  {map_color(pct_color)}")
                if "color" in el:
                    lines.append(f"#define {define_name}_COLOR  {map_color(el['color'])}")

            # Size (w/h)
            if "w" in el:
                lines.append(f"#define {define_name}_W  {el['w']}")
            if "h" in el:
                lines.append(f"#define {define_name}_H  {el['h']}")

            # Text element: font, color, datum
            if el_type == "text":
                if "font" in el:
                    lines.append(f"#define {define_name}_FONT  {v2_font_map.get(el['font'], 'LCARS_FONT_SM')}")
                if "color" in el:
                    lines.append(f"#define {define_name}_COLOR  {map_color(el['color'])}")
                if "datum" in el:
                    lines.append(f"#define {define_name}_DATUM  {datum_map.get(el['datum'], 'TL_DATUM')}")

            # vline/hline color
            if el_type in ("vline", "hline") and "color" in el:
                lines.append(f"#define {define_name}_COLOR  {map_color(el['color'])}")

            # countdownBar / statusRow color
            if el_type in ("countdownBar", "statusRow") and "color" in el:
                lines.append(f"#define {define_name}_COLOR  {map_color(el['color'])}")

        lines.append("")

    # Frame chrome defines (shared across screens, use first occurrence)
    frame_by_id = {}
    for screen in layouts.get("screens", []):
        for e in screen.get("elements", []):
            eid = e.get("id", "")
            if eid.startswith("frame_") and eid not in frame_by_id:
                frame_by_id[eid] = e

    if frame_by_id:
        lines.append("// ---- Frame Chrome ----")
        for el in frame_by_id.values():
            eid = el["id"]
            define_name = eid.upper()
            lines.append(f"#define {define_name}_X  {el['x']}")
            lines.append(f"#define {define_name}_Y  {el['y']}")
            if "w" in el:
                lines.append(f"#define {define_name}_W  {el['w']}")
            if "h" in el:
                lines.append(f"#define {define_name}_H  {el['h']}")
            if "color" in el:
                lines.append(f"#define {define_name}_COLOR  {map_color(el['color'])}")
            if "font" in el:
                lines.append(f"#define {define_name}_FONT  {v2_font_map.get(el['font'], 'LCARS_FONT_SM')}")
            if "text" in el:
                lines.append(f'#define {define_name}_TEXT  "{el["text"]}"')
        lines.append("")

    return "\n".join(lines) + "\n"


# ============================================================
# Build Manager
# ============================================================
class BuildManager:
    """Manages background builds with output buffering."""

    def __init__(self):
        self._builds = {}
        self._next_id = 0
        self._lock = threading.Lock()

    def start_build(self, env: str, project_dir: Path = None, upload: bool = False, port: str = "") -> str:
        with self._lock:
            build_id = str(self._next_id)
            self._next_id += 1

        fw_dir = project_dir or FIRMWARE_V1_DIR
        cmd = [PIO_CMD, "run", "-d", str(fw_dir), "-e", env]
        if upload:
            cmd += ["--target", "upload"]
            if port:
                cmd += ["--upload-port", port]

        try:
            proc = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, bufsize=1
            )
        except FileNotFoundError:
            self._builds[build_id] = {
                "process": None,
                "lines": [f"ERROR: PlatformIO not found at: {PIO_CMD}",
                          "Install PlatformIO or check your PATH."],
                "done": True,
                "success": False
            }
            return build_id

        build = {
            "process": proc,
            "lines": [f"$ {' '.join(cmd)}"],
            "done": False,
            "success": False
        }
        self._builds[build_id] = build

        thread = threading.Thread(target=self._reader, args=(build_id,), daemon=True)
        thread.start()

        return build_id

    def _reader(self, build_id: str):
        build = self._builds[build_id]
        proc = build["process"]
        try:
            for line in proc.stdout:
                build["lines"].append(line.rstrip())
            proc.wait()
            build["success"] = (proc.returncode == 0)
            build["lines"].append(
                f"\n{'BUILD SUCCESS' if build['success'] else 'BUILD FAILED'} (exit code {proc.returncode})"
            )
        except Exception as e:
            build["lines"].append(f"ERROR: {e}")
            build["success"] = False
        finally:
            build["done"] = True

    def get_status(self, build_id: str, from_line: int = 0) -> dict:
        build = self._builds.get(build_id)
        if not build:
            return {"error": "Unknown build ID", "done": True, "success": False, "lines": []}
        return {
            "lines": build["lines"][from_line:],
            "done": build["done"],
            "success": build["success"]
        }


# ============================================================
# Serial Monitor
# ============================================================
class SerialMonitor:
    """Background serial port reader with line buffering."""

    def __init__(self):
        self._proc = None
        self._serial = None
        self._lines = []
        self._lock = threading.Lock()
        self._connected = False
        self._port = ""

    def connect(self, port: str, baud: int = 115200) -> bool:
        self.disconnect()
        self._port = port
        self._lines = [f"--- Connecting to {port} at {baud} baud ---"]

        # Try pyserial first, fall back to PlatformIO device monitor
        try:
            import serial as pyserial
            self._serial = pyserial.Serial(port, baud, timeout=0.1)
            # Toggle DTR to reset the ESP32 so we see boot messages
            self._serial.dtr = False
            time.sleep(0.1)
            self._serial.dtr = True
            self._connected = True
            thread = threading.Thread(target=self._pyserial_reader, daemon=True)
            thread.start()
            print(f"  Serial connected (pyserial): {port}")
            return True
        except ImportError:
            print("  pyserial not available, trying PlatformIO...")
        except Exception as e:
            self._lines.append(f"ERROR: {e}")
            print(f"  Serial error: {e}")
            return False

        # Fallback: PlatformIO device monitor
        try:
            cmd = [PIO_CMD, "device", "monitor",
                   "--port", port, "--baud", str(baud),
                   "--no-reconnect", "--raw"]
            self._proc = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, bufsize=1
            )
            self._connected = True
            thread = threading.Thread(target=self._pio_reader, daemon=True)
            thread.start()
            print(f"  Serial connected (pio): {port}")
            return True
        except Exception as e:
            self._lines.append(f"ERROR: {e}")
            print(f"  Serial fallback error: {e}")
            return False

    def _pyserial_reader(self):
        """Read from pyserial directly."""
        buf = ""
        try:
            while self._connected and self._serial and self._serial.is_open:
                data = self._serial.read(256)
                if data:
                    buf += data.decode("utf-8", errors="replace")
                    while "\n" in buf:
                        line, buf = buf.split("\n", 1)
                        with self._lock:
                            self._lines.append(line.rstrip())
                else:
                    time.sleep(0.05)
        except Exception:
            pass
        finally:
            with self._lock:
                self._connected = False
                self._lines.append("--- Disconnected ---")

    def _pio_reader(self):
        """Read from PlatformIO device monitor subprocess."""
        try:
            for line in self._proc.stdout:
                with self._lock:
                    self._lines.append(line.rstrip())
        except Exception:
            pass
        finally:
            with self._lock:
                self._connected = False
                self._lines.append("--- Disconnected ---")

    def disconnect(self):
        self._connected = False
        if self._serial:
            try:
                self._serial.close()
            except Exception:
                pass
            self._serial = None
        if self._proc:
            try:
                self._proc.terminate()
                self._proc.wait(timeout=3)
            except Exception:
                try:
                    self._proc.kill()
                except Exception:
                    pass
            self._proc = None

    def get_lines(self, from_line: int = 0) -> dict:
        with self._lock:
            return {
                "lines": self._lines[from_line:],
                "connected": self._connected,
                "port": self._port,
                "total": len(self._lines)
            }

    @property
    def is_connected(self):
        return self._connected


# ============================================================
# HTTP Handler
# ============================================================
build_manager = BuildManager()
serial_monitor = SerialMonitor()

class DesignerHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(DESIGNER_DIR), **kwargs)

    def log_message(self, format, *args):
        # Quieter logging — only show API calls
        try:
            path = str(args[0]).split()[1] if args else ""
        except (IndexError, AttributeError):
            return
        if path.startswith("/api/") and not path.startswith("/api/build-status") and not path.startswith("/api/serial-read"):
            super().log_message(format, *args)

    def end_headers(self):
        # Disable caching for all static files so browser always gets latest version
        self.send_header('Cache-Control', 'no-cache, no-store, must-revalidate')
        self.send_header('Pragma', 'no-cache')
        self.send_header('Expires', '0')
        super().end_headers()

    def do_GET(self):
        parsed = urlparse(self.path)

        if parsed.path == "/api/layouts":
            self._serve_layouts()
        elif parsed.path == "/api/build-status":
            self._serve_build_status(parsed)
        elif parsed.path == "/api/serial-ports":
            self._serve_serial_ports()
        elif parsed.path == "/api/serial-read":
            self._serve_serial_read(parsed)
        else:
            super().do_GET()

    def do_POST(self):
        parsed = urlparse(self.path)
        body = self._read_body()

        if parsed.path == "/api/save":
            self._handle_save(body)
        elif parsed.path == "/api/build":
            self._handle_build(body)
        elif parsed.path == "/api/upload":
            self._handle_upload(body)
        elif parsed.path == "/api/serial-connect":
            self._handle_serial_connect(body)
        elif parsed.path == "/api/serial-disconnect":
            self._handle_serial_disconnect()
        else:
            self.send_error(404)

    # ---- API handlers ----

    def _serve_serial_ports(self):
        """List available serial/COM ports."""
        ports = []
        try:
            from serial.tools.list_ports import comports
            for p in comports():
                ports.append({
                    "port": p.device,
                    "desc": p.description or p.device,
                    "hwid": p.hwid or ""
                })
        except ImportError:
            # pyserial not installed — try PlatformIO's device list
            try:
                result = subprocess.run(
                    [PIO_CMD, "device", "list", "--json-output"],
                    capture_output=True, text=True, timeout=10
                )
                if result.returncode == 0:
                    devices = json.loads(result.stdout)
                    for d in devices:
                        ports.append({
                            "port": d.get("port", ""),
                            "desc": d.get("description", d.get("port", "")),
                            "hwid": d.get("hwid", "")
                        })
            except Exception:
                pass
        self._send_json({"ports": ports})

    def _serve_layouts(self):
        if LAYOUTS_FILE.exists():
            data = LAYOUTS_FILE.read_text(encoding="utf-8")
            self._send_json_str(data)
        else:
            self._send_json({"screens": []})

    def _serve_build_status(self, parsed):
        params = parse_qs(parsed.query)
        build_id = params.get("id", [""])[0]
        from_line = int(params.get("from", ["0"])[0])
        status = build_manager.get_status(build_id, from_line)
        self._send_json(status)

    def _handle_save(self, body):
        try:
            data = json.loads(body)
            with open(LAYOUTS_FILE, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2)
            print(f"  Saved layouts.json ({len(data.get('screens', []))} screens)")
            self._send_json({"ok": True})
        except Exception as e:
            self._send_json({"ok": False, "error": str(e)}, status=400)

    def _handle_build(self, body):
        try:
            data = json.loads(body)
            board = data.get("board", "tdisplay")
            firmware = data.get("firmware", "v1")
            env = ENV_MAP.get(board, "tdisplays3")

            if firmware == "v1":
                # v1: Generate header from saved layouts, then build
                if not LAYOUTS_FILE.exists():
                    self._send_json({"error": "No layouts.json found. Save first."}, status=400)
                    return

                layouts = json.loads(LAYOUTS_FILE.read_text(encoding="utf-8"))
                # Extract v1 screens from dual-format or legacy format
                v1_data = layouts.get("v1", layouts)
                header_content = generate_header(v1_data)
                HEADER_FILE.parent.mkdir(parents=True, exist_ok=True)
                HEADER_FILE.write_text(header_content, encoding="utf-8")
                print(f"  Generated {HEADER_FILE.name}")

                build_id = build_manager.start_build(env, project_dir=FIRMWARE_V1_DIR)
            else:
                # v2: Generate header from saved v2 layouts, then build firmware-v2/
                if not LAYOUTS_FILE.exists():
                    self._send_json({"error": "No layouts.json found. Save first."}, status=400)
                    return

                layouts = json.loads(LAYOUTS_FILE.read_text(encoding="utf-8"))
                v2_data = layouts.get("v2", {})
                if v2_data.get("screens"):
                    header_content = generate_header_v2(v2_data)
                    HEADER_V2_FILE.parent.mkdir(parents=True, exist_ok=True)
                    HEADER_V2_FILE.write_text(header_content, encoding="utf-8")
                    print(f"  Generated v2 {HEADER_V2_FILE.name}")

                build_id = build_manager.start_build(env, project_dir=FIRMWARE_V2_DIR)

            print(f"  Build started (id={build_id}, env={env}, fw={firmware})")
            self._send_json({"build_id": build_id}, status=202)
        except Exception as e:
            self._send_json({"error": str(e)}, status=500)

    def _handle_upload(self, body):
        try:
            data = json.loads(body)
            board = data.get("board", "tdisplay")
            port = data.get("port", "")
            firmware = data.get("firmware", "v1")
            env = ENV_MAP.get(board, "tdisplays3")

            if firmware == "v1":
                # Generate header first (same as build)
                if LAYOUTS_FILE.exists():
                    layouts = json.loads(LAYOUTS_FILE.read_text(encoding="utf-8"))
                    v1_data = layouts.get("v1", layouts)
                    header_content = generate_header(v1_data)
                    HEADER_FILE.parent.mkdir(parents=True, exist_ok=True)
                    HEADER_FILE.write_text(header_content, encoding="utf-8")

                project_dir = FIRMWARE_V1_DIR
            else:
                # v2: Generate header first (same as build)
                if LAYOUTS_FILE.exists():
                    layouts = json.loads(LAYOUTS_FILE.read_text(encoding="utf-8"))
                    v2_data = layouts.get("v2", {})
                    if v2_data.get("screens"):
                        header_content = generate_header_v2(v2_data)
                        HEADER_V2_FILE.parent.mkdir(parents=True, exist_ok=True)
                        HEADER_V2_FILE.write_text(header_content, encoding="utf-8")

                project_dir = FIRMWARE_V2_DIR

            build_id = build_manager.start_build(env, project_dir=project_dir, upload=True, port=port)
            port_info = f", port={port}" if port else ""
            print(f"  Upload started (id={build_id}, env={env}, fw={firmware}{port_info})")
            self._send_json({"build_id": build_id}, status=202)
        except Exception as e:
            self._send_json({"error": str(e)}, status=500)

    # ---- Serial monitor handlers ----

    def _handle_serial_connect(self, body):
        try:
            data = json.loads(body)
            port = data.get("port", "")
            baud = data.get("baud", 115200)
            if not port:
                self._send_json({"error": "No port specified"}, status=400)
                return
            ok = serial_monitor.connect(port, baud)
            if ok:
                self._send_json({"ok": True, "port": port})
            else:
                # Return the last error line from the monitor's buffer
                lines = serial_monitor.get_lines()["lines"]
                err = lines[-1] if lines else "Connection failed"
                self._send_json({"ok": False, "error": err})
        except Exception as e:
            self._send_json({"error": str(e)}, status=500)

    def _handle_serial_disconnect(self):
        serial_monitor.disconnect()
        self._send_json({"ok": True})

    def _serve_serial_read(self, parsed):
        params = parse_qs(parsed.query)
        from_line = int(params.get("from", ["0"])[0])
        status = serial_monitor.get_lines(from_line)
        self._send_json(status)

    # ---- Helpers ----

    def _read_body(self) -> bytes:
        length = int(self.headers.get("Content-Length", 0))
        return self.rfile.read(length)

    def _send_json(self, data: dict, status: int = 200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_json_str(self, json_str: str, status: int = 200):
        body = json_str.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


# ============================================================
# Main
# ============================================================
def main():
    print(f"LCARS Designer Server")
    print(f"  Designer:     {DESIGNER_DIR}")
    print(f"  Firmware v1:  {FIRMWARE_V1_DIR}")
    print(f"  Firmware v2:  {FIRMWARE_V2_DIR}")
    print(f"  PIO:          {PIO_CMD}")
    print(f"  Layouts:      {LAYOUTS_FILE}")
    print(f"  Header (v1):  {HEADER_FILE}")
    print(f"  Header (v2):  {HEADER_V2_FILE}")
    print()

    server = http.server.HTTPServer(("", PORT), DesignerHandler)
    print(f"  Serving on http://localhost:{PORT}")
    print(f"  Press Ctrl+C to stop\n")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        server.server_close()


if __name__ == "__main__":
    main()
